services:
  frontend:
    build: ./videochat_frontend
    ports:
      - "3000:3000"
    networks:
      - app-network
  main_backend:
    build: ./videochat_backend
    ports:
      - "3200:3200"
    networks:
      - app-network
  auth_backend:
    build: ./AuthService
    ports:
      - "4000:4000"
    networks:
      - app-network
  blur_backend:
    build: ./enhancements_backend/blur
    ports: 
      - "5001:5001"
    networks:
      - app-network
  noise_backend:
    build: ./enhancements_backend/noise
    ports: 
      - "5002:5002"
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
